/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HarjutaRouteImport } from './routes/harjuta'
import { Route as HarjutusedRouteImport } from './routes/harjutused'
import { Route as LoodRouteImport } from './routes/lood'
import { Route as MangudRouteImport } from './routes/mangud'
import { Route as MinaRouteImport } from './routes/mina'
import { Route as SilbidRouteImport } from './routes/silbid'
import { Route as VanemateleRouteImport } from './routes/vanematele'
import { Route as LuguIdRouteImport } from './routes/lugu.$id'
import { Route as MangKindRouteImport } from './routes/mang.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarjutaRoute = HarjutaRouteImport.update({
  id: '/harjuta',
  path: '/harjuta',
  getParentRoute: () => rootRouteImport,
} as any)
const HarjutusedRoute = HarjutusedRouteImport.update({
  id: '/harjutused',
  path: '/harjutused',
  getParentRoute: () => rootRouteImport,
} as any)
const LoodRoute = LoodRouteImport.update({
  id: '/lood',
  path: '/lood',
  getParentRoute: () => rootRouteImport,
} as any)
const MangudRoute = MangudRouteImport.update({
  id: '/mangud',
  path: '/mangud',
  getParentRoute: () => rootRouteImport,
} as any)
const MinaRoute = MinaRouteImport.update({
  id: '/mina',
  path: '/mina',
  getParentRoute: () => rootRouteImport,
} as any)
const SilbidRoute = SilbidRouteImport.update({
  id: '/silbid',
  path: '/silbid',
  getParentRoute: () => rootRouteImport,
} as any)
const VanemateleRoute = VanemateleRouteImport.update({
  id: '/vanematele',
  path: '/vanematele',
  getParentRoute: () => rootRouteImport,
} as any)
const LuguIdRoute = LuguIdRouteImport.update({
  id: '/lugu/$id',
  path: '/lugu/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangKindRoute = MangKindRouteImport.update({
  id: '/mang/$kind',
  path: '/mang/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harjuta': typeof HarjutaRoute
  '/harjutused': typeof HarjutusedRoute
  '/lood': typeof LoodRoute
  '/mangud': typeof MangudRoute
  '/mina': typeof MinaRoute
  '/silbid': typeof SilbidRoute
  '/vanematele': typeof VanemateleRoute
  '/lugu/$id': typeof LuguIdRoute
  '/mang/$kind': typeof MangKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harjuta': typeof HarjutaRoute
  '/harjutused': typeof HarjutusedRoute
  '/lood': typeof LoodRoute
  '/mangud': typeof MangudRoute
  '/mina': typeof MinaRoute
  '/silbid': typeof SilbidRoute
  '/vanematele': typeof VanemateleRoute
  '/lugu/$id': typeof LuguIdRoute
  '/mang/$kind': typeof MangKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harjuta': typeof HarjutaRoute
  '/harjutused': typeof HarjutusedRoute
  '/lood': typeof LoodRoute
  '/mangud': typeof MangudRoute
  '/mina': typeof MinaRoute
  '/silbid': typeof SilbidRoute
  '/vanematele': typeof VanemateleRoute
  '/lugu/$id': typeof LuguIdRoute
  '/mang/$kind': typeof MangKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/harjuta'
    | '/harjutused'
    | '/lood'
    | '/mangud'
    | '/mina'
    | '/silbid'
    | '/vanematele'
    | '/lugu/$id'
    | '/mang/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/harjuta'
    | '/harjutused'
    | '/lood'
    | '/mangud'
    | '/mina'
    | '/silbid'
    | '/vanematele'
    | '/lugu/$id'
    | '/mang/$kind'
  id:
    | '__root__'
    | '/'
    | '/harjuta'
    | '/harjutused'
    | '/lood'
    | '/mangud'
    | '/mina'
    | '/silbid'
    | '/vanematele'
    | '/lugu/$id'
    | '/mang/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarjutaRoute: typeof HarjutaRoute
  HarjutusedRoute: typeof HarjutusedRoute
  LoodRoute: typeof LoodRoute
  MangudRoute: typeof MangudRoute
  MinaRoute: typeof MinaRoute
  SilbidRoute: typeof SilbidRoute
  VanemateleRoute: typeof VanemateleRoute
  LuguIdRoute: typeof LuguIdRoute
  MangKindRoute: typeof MangKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harjuta': {
      id: '/harjuta'
      path: '/harjuta'
      fullPath: '/harjuta'
      preLoaderRoute: typeof HarjutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harjutused': {
      id: '/harjutused'
      path: '/harjutused'
      fullPath: '/harjutused'
      preLoaderRoute: typeof HarjutusedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lood': {
      id: '/lood'
      path: '/lood'
      fullPath: '/lood'
      preLoaderRoute: typeof LoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangud': {
      id: '/mangud'
      path: '/mangud'
      fullPath: '/mangud'
      preLoaderRoute: typeof MangudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mina': {
      id: '/mina'
      path: '/mina'
      fullPath: '/mina'
      preLoaderRoute: typeof MinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silbid': {
      id: '/silbid'
      path: '/silbid'
      fullPath: '/silbid'
      preLoaderRoute: typeof SilbidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanematele': {
      id: '/vanematele'
      path: '/vanematele'
      fullPath: '/vanematele'
      preLoaderRoute: typeof VanemateleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugu/$id': {
      id: '/lugu/$id'
      path: '/lugu/$id'
      fullPath: '/lugu/$id'
      preLoaderRoute: typeof LuguIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mang/$kind': {
      id: '/mang/$kind'
      path: '/mang/$kind'
      fullPath: '/mang/$kind'
      preLoaderRoute: typeof MangKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarjutaRoute: HarjutaRoute,
  HarjutusedRoute: HarjutusedRoute,
  LoodRoute: LoodRoute,
  MangudRoute: MangudRoute,
  MinaRoute: MinaRoute,
  SilbidRoute: SilbidRoute,
  VanemateleRoute: VanemateleRoute,
  LuguIdRoute: LuguIdRoute,
  MangKindRoute: MangKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
